# Generated by Django 5.1 on 2024-09-03 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0002_carrera_code_curso_code_estudiante_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
