# Generated by Django 5.1 on 2024-09-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0003_alter_carrera_code_alter_curso_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
